import Header from './components/Header'
import React from 'react'

type Props = {}
export const metadata = {
  title: 'Restaurant of Open Table',
  description: 'Generated by Open Table',
}

const Layout = ({
  children,
  params,
}: {
  children: React.ReactNode
  params: { slug: string }
}) => {
  return (
    <main>
      <Header name={params.slug} />
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        {children}
      </div>
    </main>
  )
}

export default Layout
